#! /bin/sh


polybar &
pgrep -x sxhkd > /dev/null || sxhkd &

INTERNAL_MONITOR="eDP-1"
EXTERNAL_MONITOR="HDMI-1"

if [[ "$1" = 0 ]]; then
	if xrandr -q | grep "${EXTERNAL_MONITOR} connected"; then
		xrandr --output ${EXTERNAL_MONITOR} --mode 1920x1080 --left ${INTERNAL_MONITOR}
		bspc monitor "${INTERNAL_MONITOR}" -d one two three four 
		bspc monitor "${EXTERNAL_MONITOR}" -d five six seven eight
		bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"

	else
		bspc monitor "${INTERNAL_MONITOR}" -d one two three four five six seven eight
	fi
fi 

 if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
  ~/Documents/scripts/monitorAdd -i $INTERNAL_MONITOR -e $EXTERNAL_MONITOR
else
  if [[ $(bspc query -M  | wc -l) -eq 2 ]]; then
  ~/Documents/scripts/monitorRemove -i $INTERNAL_MONITOR -e $EXTERNAL_MONITOR
  fi
fi

bspc config border_width         2
bspc config window_gap          8

bspc config active_border_color \#2b3052
bspc config normal_border_color \#2b3052

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
